---
- hosts: all
  become: true
  become_method: sudo 
  tasks: 
    - name: Install vim/tree/telnet on Debian/Ubuntu
      include: Debian_Ubuntu.yaml
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
      ignore_errors: True

    - name: Install vim/tree/telnet on CentOS 
      include: CentOS.yaml
      when: ansible_os_family == 'CentOS'
      ignore_errors: True
    
    - name: Create files with date and size 
      include: file_creation_size_date.yaml
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS'
      ignore_errors: True

    - name: Archive files by age
      include: finding_archiving_age.yaml
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS'
      ignore_errors: True

    - name: Archive files by size
      include: finding_archiving_size.yaml
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS'
      ignore_errors: True
